### PR TITLE
v1

### PR DESCRIPTION
**Pull request by disaltzman**

### CODE REVIEW

**Comment by rhancockn** [comment]
Although this passed the check (due to an error in the test code), it is technically incorrect because the case of your file names doesn't match the case of the condition names in the file. 
+1 for making the test script crash without failing.

**Comment by disaltzman** [comment]
I fixed the case issue in the code and ran it again, but when I committed it it did not update the files in the "data" directory on GitHub.

**Comment by rhancockn** [comment]
Did you `git rm` the old data/ files and `git add` the new files before committing?

**Comment by rhancockn** [comment]
Looks good!

**Pull request closed without merging**
